config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :pages
    resources :partials
    resources :slugs, :only => [:index]
    resources :setting_types
    resources :users
    resources :template_layouts
  end

  get 'admin', :to => 'admin#index'

  resource :session, :only => [:new, :create, :destroy]
  
  get 'login', :to => 'sessions#new'
  get 'logout', :to => 'sessions#destroy'
  

  root :to => 'slugs#show', :defaults => { :slug => 'home' }

  get '/:slug', :to => 'slugs#show'

  {
    404 => :not_found,
    422 => :bad_request, 
    500 => :internal_server_error
  }.each do |code, route_name|
    get "/#{code}", :to => 'errors#show', :defaults => { :code => code }, :as => route_name
  end

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  belongs_to :file_type
  belongs_to :data_fileable, :polymorphic => true


  def partials
    partial_names = body.scan(/\{% partial .?(\w+).?/).flatten
    Partial.where('name IN [?]', partial_names)
  end


  def render(data={})
    rendered = file_type.markdown? ? RDiscount.new(body).to_html : body
    rendered = file_type.liquid? ? Liquid::Template.parse(rendered).render(data) : rendered
    rendered.html_safe
  end
end

app/models/file_type.rb
class FileType < ActiveRecord::Base
  HTML = 'html'
  MARKDOWN = 'md'
  LIQUID_HTML = 'html.liquid'
  LIQUID_MARKDOWN = 'md.liquid'


  has_many :data_files, :dependent => :nullify


  def liquid?
    [LIQUID_HTML, LIQUID_MARKDOWN].include?(extension)
  end


  def markdown?
    [MARKDOWN, LIQUID_MARKDOWN].include?(extension)
  end


  def html?
    [HTML, LIQUID_HTML].include?(extension)
  end
end

app/models/liquid_partial_tag.rb
class LiquidPartialTag < Liquid::Tag
  def initialize(tag_name, params, tokens)
    super
    splitted = params.split(',')
    partial_name = splitted[0]
    partial_name = partial_name.match(/('|")?([^'"]+)('|")?/)
    if partial_name && partial_name[2]
      @name = partial_name[2].strip
    end
    if splitted.length > 1
      @params = parse_params(splitted[1..-1].join(',')) # TODO parse this better
    else
      @params = {}
    end
  end


  def render(context)
    context.environments.each do |env|
      @params['_env'].each do |params_key, params_value|
        env.each do |env_key, env_value|
          if params_value == env_key
            @params[params_key] = env_value
          end
        end
      end
    end
    partial = Partial.find_by_name(@name)
    partial.data_file.render(@params)
  end




  private
  def parse_params(params)
    YAML.load(params)
  end
end

Liquid::Template.register_tag('partial', LiquidPartialTag)

app/models/page.rb
class Page < ActiveRecord::Base
  include UniquelyIdentifiable


  unique_id_seed :title
  unique_id_attribute :uid


  belongs_to :parent, :class_name => 'Page'
  has_one :slug, :as => :sluggable, :dependent => :destroy
  has_one :view, :as => :viewable, :dependent => :destroy


  validates :title,
            :presence => true,
            :uniqueness => true

  validates :view,
            :presence => true,
            :on => :update

  validates :slug,
            :presence => true,
            :on => :update

  validate :parent_cannot_be_self


  accepts_nested_attributes_for :slug
  accepts_nested_attributes_for :view




  private
  def parent_cannot_be_self
    if parent == self
      errors.add(:parent, 'A page cannot have itself as a parent')
    end
  end
end

app/models/partial.rb
class Partial < ActiveRecord::Base
  has_one :data_file, :as => :data_fileable, :dependent => :destroy

  accepts_nested_attributes_for :data_file

  def rendered_in
    DataFile.where(%Q;body LIKE '%\{\% partial _#{name}_%';)
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :setting_type

  # TODO add validations
end

app/models/setting_type.rb
class SettingType < ActiveRecord::Base
  has_many :settings, :dependent => :nullify

  # TODO add validations
  # TODO validate uniqueness of [setting_type_id, key]

  accepts_nested_attributes_for :settings
end

app/models/slug.rb
class Slug < ActiveRecord::Base
  belongs_to :sluggable, :polymorphic => true

  validates :uri,
            :presence => true,
            :uniqueness => true
end

app/models/template_layout.rb
class TemplateLayout < ActiveRecord::Base
  has_one :data_file, :as => :data_fileable, :dependent => :destroy
  has_many :views, :dependent => :nullify

  accepts_nested_attributes_for :data_file
end

app/models/user.rb
class User < ActiveRecord::Base
  include UniquelyIdentifiable


  unique_id_seed :email
  unique_id_attribute :auth_token


  has_secure_password

  validates :email,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /@/ }

  validates :username,
            :presence => true,
            :length => { :in => 8..32 },
            :format => { :with => /\A[\w\d]+\z/ }

  validates :password,
            :length => { :in => 8..32 },
            :format => { :without => /\s/ },
            :allow_nil => true


  before_destroy :deny_destroy_if_last


  def self.find_by_username_or_email(username_or_email)
    User.where(
      'email = ? OR username = ?',
      username_or_email,
      username_or_email
    ).first
  end




  private
  def deny_destroy_if_last
    is_last = User.count == 1
    if is_last
      errors.add(:base, 'Cannot destroy last user')
    end
    !is_last
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :viewable, :polymorphic => true
  belongs_to :template_layout
  has_one :data_file, :as => :data_fileable, :dependent => :destroy

  accepts_nested_attributes_for :data_file
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_login


  layout 'admin'


  def index
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_action :set_code


  def show
    render @code, :status => @code
  end




  private
  def set_code
    p [params]
    @code = [404, 422, 500].include?(params[:code].to_i) ? params[:code] : 500
  end
end

app/controllers/slugs_controller.rb
class SlugsController < ApplicationController
  before_action :set_slug


  def show
    @data = {}
    Setting.all.to_a.each { |setting| @data[setting.key] = setting.value }
  end





  private
  def set_slug
    @slug = Slug.find_by_uri(params[:slug])
    redirect_to not_found_path unless @slug
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, class_name=nil, &block)
    class_name ||= object.class.to_s
    presenter = "#{class_name}Presenter".constantize.new(object, self)
    if block_given?
      yield(presenter) 
    else
      block.call(presenter)
    end
  end


  def error_messages_for(object, field=nil)
    errors = field ? object.errors[field] : object.errors.full_messages
    errors.each do |error|
      yield(error)
    end 
  end


  def flash_css_class(key)
    if ['notice', 'error'].include?(key)
      key == 'notice' ? 'info' : 'danger'
    else
      key.to_s
    end
  end


  def fa(*args)
    classes = args.map { |arg| "fa-#{arg}" }.join(' ')
    %Q[<i class="fa #{classes}"></i>].html_safe
  end
end

app/helpers/data_file_helper.rb
module DataFileHelper
  def data_fileable_link_for(data_file)
    data_fileable = data_file.data_fileable
    if data_file.data_fileable.is_a?(View)
      resource = data_fileable.viewable
      type = data_fileable.viewable.class.to_s
      text = data_fileable.viewable.title
    else
      resource = data_fileable
      type = data_fileable.class.to_s
      text = data_fileable.name
    end
    "#{type} - #{link_to(text, polymorphic_path([:admin, resource]))}".html_safe
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slugs_helper.rb
module SlugsHelper
end

app/views/admin/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Bideo Wego Blogger!</h1>
  <p>
    <%= link_to('Get started', admin_user_path(current_user), :class => 'btn btn-primary btn-lg') %>
  </p>
</div>

app/views/admin/pages/_form.html.erb
<%= render :partial => 'admin/shared/errors', :locals => { :object => page } %>

<%= form_for([:admin, page]) do |f| %>

  <% if page.persisted? %>
    <div class="form-group">
      <h2 class="form-control-static"><em>ID:</em> <%= page.id %></h2>
    </div>
  <% end %>

  <!-- Slug -->
  <%= f.fields_for(:slug) do |slug_fields| %>
    <div class="form-group">
      <%= slug_fields.label(:uri) %>
      <%= slug_fields.text_field(:uri, :class => 'form-control') %>
    </div>
    <%= slug_fields.hidden_field(:sluggable_type) %>
    <%= slug_fields.hidden_field(:sluggable_id) %>
  <% end %>

  <!-- Page -->
  <div class="form-group">
    <%= f.label(:title) %>
    <%= f.text_field(:title, :class => 'form-control') %>
  </div>
  <div class="form-group">
    <%= f.label(:parent) %>
    <%= f.collection_select(
      :parent_id,
      Page.all.reject { |parent| parent == page },
      :id,
      :title,
      { :include_blank => true },
      { :class => 'form-control' }
    ) %>
  </div>

  <!-- View -->
  <%= f.fields_for(:view) do |view_fields| %>
    <div class="form-group">
      <%= view_fields.label(:template_layout) %>
      <%= view_fields.collection_select(
        :template_layout_id,
        TemplateLayout.all,
        :id,
        :name,
        { :include_blank => true },
        { :class => 'form-control' }
      ) %>
      <%= view_fields.hidden_field(:viewable_type) %>
      <%= view_fields.hidden_field(:viewable_id) %>
    </div>


    <!-- Data File -->
    <%= view_fields.fields_for(:data_file) do |data_file_fields| %>
      <div class="form-group">
        <%= data_file_fields.label(:body) %>
        <%= data_file_fields.text_area(:body, :class => 'form-control') %>
      </div>
      <div class="form-group">
        <%= data_file_fields.label(:file_type) %>
        <%= data_file_fields.collection_select(
          :file_type_id,
          FileType.all,
          :id,
          :name,
          {},
          { :class => 'form-control' }
        ) %>
      </div>
      <%= data_file_fields.hidden_field(:data_fileable_type) %>
      <%= data_file_fields.hidden_field(:data_fileable_id) %>
    <% end %>
  <% end %>

  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/admin/pages/edit.html.erb
<header class="page-header">
  <h1>
    <%= fa('file') %> Edit Page
    <small>
      <%= link_to(@page.title, admin_page_path(@page)) %>
    </small>
  </h1>
</header>

<%= render :partial => 'form', :locals => { :page => @page } %>

app/views/admin/pages/index.html.erb
<header class="page-header">
  <h1>
    <%= fa('file') %> Pages
    <small>
      <%= link_to(fa('plus') + ' New Page', new_admin_page_path) %>
    </small>
  </h1>
</header>


<% if @pages.present? %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th><th>Title</th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.id %></td>
          <td><%= link_to(page.title, admin_page_path(page)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p class="text-danger">Why for are there no more pages no more?</p>

<% end %>

app/views/admin/pages/new.html.erb
<header class="page-header">
  <h1>
    <%= fa('file') %> New Page
  </h1>
</header>

<%= render :partial => 'form', :locals => { :page => @page } %>

app/views/admin/pages/show.html.erb
<header class="page-header">
  <h1>
    <%= fa('file') %> Page
    <small>
      <%= link_to(@page.title, admin_page_path(@page)) %>
    </small>
  </h1>
</header>

<div class="actions">
  <%= link_to(fa('pencil-square-o') + ' Edit', edit_admin_page_path(@page), :class => 'btn btn-default') %>
  <%= link_to(fa('close') + ' Delete', admin_page_path(@page), :method => :delete, :class => 'btn btn-danger') %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Key</th><th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Title</td><td><%= @page.title %></td>
    </tr>
    <tr>
      <td>Layout</td><td><%= @page.view.template_layout ? @page.view.template_layout.name : '-' %></td>
    </tr>
    <tr>
      <td>Parent</td><td><%= @page.parent ? @page.parent.title : '-' %></td>
    </tr>
  </tbody>
</table>

app/views/admin/shared/_errors.html.erb
<% if object.errors.present? %>
  <div class="alert alert-danger">
    <%
    field ||= nil
    error_messages_for(object, field) do |error|
    %>
      <%= error %>
      <br/>
    <% end %>
  </div>
<% end %>

app/views/admin/shared/_flash.html.erb
<% unless flash.empty? %>

  <% flash.each do |key, value| %>
    <div class="main-flash alert alert-<%= flash_css_class(key) %>">
      <%= value %>
    </div>
  <% end %>

<% end %>

app/views/admin/shared/_meta.html.erb
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<![endif]-->

<!-- HTML5 Shim -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<meta name="twitter:card" content="TODO fill in"/>
<meta name="twitter:site" content="TODO fill in"/>
<meta name="twitter:creator" content="TODO fill in"/>

<meta property="og:title" content="TODO fill in"/>
<meta property="og:site_name" content="TODO fill in"/>
<meta property="og:url" content="<%= root_url %>"/>
<meta property="og:description" content="TODO fill in"/>
<meta property="og:image:width" content="TODO fill in"/>
<meta property="og:image:height" content="TODO fill in"/>
<meta property="og:image" content="<%= root_url %>assets/images/ograph.jpg?v=1"/>

app/views/admin/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if signed_in_user? %>
        <%= link_to(fa('dashboard') + ' Dashboard', admin_path, :class => 'navbar-brand') %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <%= link_to(fa('home') + ' Home', root_path) %>
        </li>        
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if signed_in_user? %>

          <li>
            <%= link_to(fa('user') + ' Users', admin_users_path) %>
          </li>
          <li>
            <%= link_to(fa('gears') + ' Setting Types', admin_setting_types_path) %>
          </li>
          <li>
            <%= link_to(fa('link') + ' Slugs', admin_slugs_path) %>
          </li>
          <li>
            <%= link_to(fa('file') + ' Pages', admin_pages_path) %>
          </li>
          <li>
            <%= link_to(fa('file-o') + ' Template Layouts', admin_template_layouts_path) %>
          </li>
          <li>
            <%= link_to(fa('file-code-o') + ' Partials', admin_partials_path) %>
          </li>
          <li>
            <%= link_to(fa('power-off') + ' Logout', session_path, :method => :delete) %>
          </li>

        <% else %>

          <li>
            <%= link_to(fa('power-off') + ' Login', login_path) %>
          </li>
          
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= render :partial => 'shared/meta' %>

    <title>Bideo Wego Blogger</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body id="<%= controller_name + '-' + action_name %>">

    <%= render :partial => 'admin/shared/nav' %>
    <%= render :partial => 'admin/shared/flash' %>

    <main class="container">
      <div class="row">
        <div class="col-xs-12">
          
          <%= yield %>

        </div>
      </div>
    </main>

    <!-- Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<%= yield %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= fa('code') %> Public Navigation</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">

       <li>
         <a href="#">Public Link</a>
       </li>

      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>