config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :pages
    resources :partials
    resources :slugs, :only => [:index]
    resources :setting_types
    resources :users
    resources :template_layouts
  end

  get 'admin', :to => 'admin#index'

  resource :session, :only => [:new, :create, :destroy]
  
  get 'login', :to => 'sessions#new'
  get 'logout', :to => 'sessions#destroy'
  

  root :to => 'slugs#show', :defaults => { :slug => 'home' }

  get '/:slug', :to => 'slugs#show'

  {
    404 => :not_found,
    422 => :bad_request, 
    500 => :internal_server_error
  }.each do |code, route_name|
    get "/#{code}", :to => 'errors#show', :defaults => { :code => code }, :as => route_name
  end

end

app/models/template_layout.rb
class TemplateLayout < ActiveRecord::Base
  has_one :data_file, :as => :data_fileable, :dependent => :destroy
  has_many :views, :dependent => :nullify

  accepts_nested_attributes_for :data_file
end

app/controllers/admin/template_layouts_controller.rb
class Admin::TemplateLayoutsController < AdminController
  before_action :set_template_layout, :except => [:index, :new, :create]


  def index
    @template_layouts = TemplateLayout.all
  end


  def show
  end


  def new
    @template_layout = TemplateLayout.new
    @template_layout.build_data_file(:file_type_id => FileType.where(:extension => 'html.liquid').first.id)
  end


  def edit
  end


  def create
    @template_layout = TemplateLayout.new(template_layout_params)
    if @template_layout.save
      flash[:success] = 'Template Layout created'
      redirect_to admin_template_layout_path(@template_layout)
    else
      flash[:error] = 'Template Layout not created'
      render :new
    end
  end


  def update
    if @template_layout.update(template_layout_params)
      flash[:success] = 'Template Layout updated'
      redirect_to admin_template_layout_path(@template_layout)
    else
      flash[:error] = 'Template Layout not updated'
      render :edit
    end
  end


  def destroy
    if @template_layout.destroy
      flash[:success] = 'Template Layout destroyed'
    else
      flash[:error] = 'Template Layout not destroyed'
    end
    redirect_to admin_template_layouts_path
  end




  private
  def set_template_layout
    @template_layout = TemplateLayout.find_by_id(params[:id])
    redirect_to :back, :flash => { :error => 'TemplateLayout not found' } unless @template_layout
  end


  def template_layout_params
    params.require(:template_layout).permit(
      :name,
      :data_file_attributes => [
        :id,
        :body,
        :data_fileable_type,
        :data_fileable_id,
        :file_type_id
      ]
    )
  end
end

app/helpers/admin/template_layouts_helper.rb
module Admin::TemplateLayoutsHelper
end

app/views/admin/template_layouts/_form.html.erb
<%= render :partial => 'admin/shared/errors', :locals => { :object => template_layout } %>

<%= form_for([:admin, template_layout]) do |f| %>

  <% if template_layout.persisted? %>
    <div class="form-group">
      <h2 class="form-control-static"><em>ID:</em> <%= template_layout.id %></h2>
    </div>
  <% end %>

  <!-- Template Layout -->
  <div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, :class => 'form-control') %>
  </div>

  <!-- Data File -->
  <%= f.fields_for(:data_file) do |data_file_fields| %>
    <div class="form-group">
      <%= data_file_fields.label(:body) %>
      <%= data_file_fields.text_area(:body, :class => 'form-control') %>
    </div>
    <%= data_file_fields.hidden_field(:file_type_id) %>
    <%= data_file_fields.hidden_field(:data_fileable_type) %>
    <%= data_file_fields.hidden_field(:data_fileable_id) %>
  <% end %>

  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/admin/template_layouts/edit.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-o') %> Edit Template Layout
    <small>
      <%= link_to(@template_layout.name, admin_template_layout_path(@template_layout)) %>
    </small>
  </h1>
</header>

<%= render :partial => 'form', :locals => { :template_layout => @template_layout } %>

app/views/admin/template_layouts/index.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-o') %> Template Layouts
    <small>
      <%= link_to(fa('plus') + ' New Template Layout', new_admin_template_layout_path) %>
    </small>
  </h1>
</header>


<% if @template_layouts.present? %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th><th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @template_layouts.each do |template_layout| %>
        <tr>
          <td><%= template_layout.id %></td>
          <td><%= link_to(template_layout.name, admin_template_layout_path(template_layout)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p class="text-danger">Why for are there no more template layouts no more?</p>

<% end %>

app/views/admin/template_layouts/new.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-o') %> New Template Layout
  </h1>
</header>

<%= render :partial => 'form', :locals => { :template_layout => @template_layout } %>

app/views/admin/template_layouts/show.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-o') %> Template Layout
    <small>
      <%= link_to(@template_layout.name, admin_template_layout_path(@template_layout)) %>
    </small>
  </h1>
</header>

<div class="actions">
  <%= link_to(fa('pencil-square-o') + ' Edit', edit_admin_template_layout_path(@template_layout), :class => 'btn btn-default') %>
  <%= link_to(fa('close') + ' Delete', admin_template_layout_path(@template_layout), :method => :delete, :class => 'btn btn-danger') %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Key</th><th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>ID</td><td><%= @template_layout.id %></td>
    </tr>
    <tr>
      <td>Name</td><td><%= @template_layout.name %></td>
    </tr>
    <tr>
      <td>Used In</td>
      <td>
        <% @template_layout.views.map do |view| %>
          <%= link_to("#{view.viewable.class} - #{view.viewable.title}", polymorphic_path([:admin, view.viewable])) %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>