config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :pages
    resources :partials
    resources :slugs, :only => [:index]
    resources :setting_types
    resources :users
    resources :template_layouts
  end

  get 'admin', :to => 'admin#index'

  resource :session, :only => [:new, :create, :destroy]
  
  get 'login', :to => 'sessions#new'
  get 'logout', :to => 'sessions#destroy'
  

  root :to => 'slugs#show', :defaults => { :slug => 'home' }

  get '/:slug', :to => 'slugs#show'

  {
    404 => :not_found,
    422 => :bad_request, 
    500 => :internal_server_error
  }.each do |code, route_name|
    get "/#{code}", :to => 'errors#show', :defaults => { :code => code }, :as => route_name
  end

end

app/models/partial.rb
class Partial < ActiveRecord::Base
  has_one :data_file, :as => :data_fileable, :dependent => :destroy

  accepts_nested_attributes_for :data_file

  def rendered_in
    DataFile.where(%Q;body LIKE '%\{\% partial _#{name}_%';)
  end
end

app/controllers/admin/partials_controller.rb
class Admin::PartialsController < AdminController
  before_action :set_partial, :except => [:index, :new, :create]


  def index
    @partials = Partial.all
  end


  def show
  end


  def new
    @partial = Partial.new
    @partial.build_data_file
  end


  def edit
  end


  def create
    @partial = Partial.new(partial_params)
    if @partial.save
      flash[:success] = 'Partial created'
      redirect_to admin_partial_path(@partial)
    else
      flash[:error] = 'Partial not created'
      render :new
    end
  end


  def update
    if @partial.update(partial_params)
      flash[:success] = 'Partial updated'
      redirect_to admin_partial_path(@partial)
    else
      flash[:error] = 'Partial not updated'
      render :edit
    end
  end


  def destroy
    if @partial.destroy
      flash[:success] = 'Partial destroyed'
    else
      flash[:error] = 'Partial not destroyed'
    end
    redirect_to admin_partials_path
  end




  private
  def set_partial
    @partial = Partial.find_by_id(params[:id])
    redirect_to :back, :flash => { :error => 'Partial not found' } unless @partial
  end


  def partial_params
    params.require(:partial).permit(
      :name,
      :data_file_attributes => [
        :id,
        :body,
        :data_fileable_type,
        :data_fileable_id,
        :file_type_id
      ]
    )
  end
end

app/helpers/admin/partials_helper.rb
module Admin::PartialsHelper
end

app/views/admin/partials/_form.html.erb
<%= render :partial => 'admin/shared/errors', :locals => { :object => partial } %>

<%= form_for([:admin, partial]) do |f| %>

  <% if partial.persisted? %>
    <div class="form-group">
      <h2 class="form-control-static"><em>ID:</em> <%= partial.id %></h2>
    </div>
  <% end %>

  <!-- Template Layout -->
  <div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, :class => 'form-control') %>
  </div>

  <!-- Data File -->
  <%= f.fields_for(:data_file) do |data_file_fields| %>
    <div class="form-group">
      <%= data_file_fields.label(:body) %>
      <%= data_file_fields.text_area(:body, :class => 'form-control') %>
    </div>
    <div class="form-group">
      <%= data_file_fields.label(:file_type) %>
      <%= data_file_fields.collection_select(
        :file_type_id,
        FileType.all,
        :id,
        :name,
        {},
        { :class => 'form-control' }
      ) %>
    </div>
    <%= data_file_fields.hidden_field(:data_fileable_type) %>
    <%= data_file_fields.hidden_field(:data_fileable_id) %>
  <% end %>

  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/admin/partials/edit.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-code-o') %> Edit Partial
    <small>
      <%= link_to(@partial.name, admin_partial_path(@partial)) %>
    </small>
  </h1>
</header>

<%= render :partial => 'form', :locals => { :partial => @partial } %>

app/views/admin/partials/index.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-code-o') %> Partials
    <small>
      <%= link_to(fa('plus') + ' New Partial', new_admin_partial_path) %>
    </small>
  </h1>
</header>


<% if @partials.present? %>

  <table class="table">
    <thead>
      <tr>
        <td>ID</td><td>Name</td>
      </tr>
    </thead>
    <tbody>
      <% @partials.each do |partial| %>
        <tr>
          <td><%= partial.id %></td>
          <td><%= link_to(partial.name, admin_partial_path(partial)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p class="text-danger">Why for are there no more partials no more?</p>

<% end %>

app/views/admin/partials/new.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-code-o') %> New Partial
  </h1>
</header>

<%= render :partial => 'form', :locals => { :partial => @partial } %>

app/views/admin/partials/show.html.erb
<header class="page-header">
  <h1>
    <%= fa('file-code-o') %> Partial
    <small>
      <%= link_to(@partial.name, admin_partial_path(@partial)) %>
    </small>
  </h1>
</header>

<div class="actions">
  <%= link_to(fa('pencil-square-o') + ' Edit', edit_admin_partial_path(@partial), :class => 'btn btn-default') %>
  <%= link_to(fa('close') + ' Delete', admin_partial_path(@partial), :method => :delete, :class => 'btn btn-danger') %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Key</th><th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>ID</td><td><%= @partial.id %></td>
    </tr>
    <tr>
      <td>Name</td><td><%= @partial.name %></td>
    </tr>
    <tr>
      <td>Rendered In</td>
      <td>
        <% if @partial.rendered_in.empty? %>

          <p class="text-danger">Not rendered in any data files</p>

        <% else %>

            <% @partial.rendered_in.each do |data_file| %>
              <p>
                <%= data_fileable_link_for(data_file) %>
              </p>
            <% end %>

        <% end %>
      </td>
    </tr>
  </tbody>
</table>