config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :pages
    resources :partials
    resources :slugs, :only => [:index]
    resources :setting_types
    resources :users
    resources :template_layouts
  end

  get 'admin', :to => 'admin#index'

  resource :session, :only => [:new, :create, :destroy]
  
  get 'login', :to => 'sessions#new'
  get 'logout', :to => 'sessions#destroy'
  

  root :to => 'slugs#show', :defaults => { :slug => 'home' }

  get '/:slug', :to => 'slugs#show'

  {
    404 => :not_found,
    422 => :bad_request, 
    500 => :internal_server_error
  }.each do |code, route_name|
    get "/#{code}", :to => 'errors#show', :defaults => { :code => code }, :as => route_name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include UniquelyIdentifiable


  unique_id_seed :email
  unique_id_attribute :auth_token


  has_secure_password

  validates :email,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /@/ }

  validates :username,
            :presence => true,
            :length => { :in => 8..32 },
            :format => { :with => /\A[\w\d]+\z/ }

  validates :password,
            :length => { :in => 8..32 },
            :format => { :without => /\s/ },
            :allow_nil => true


  before_destroy :deny_destroy_if_last


  def self.find_by_username_or_email(username_or_email)
    User.where(
      'email = ? OR username = ?',
      username_or_email,
      username_or_email
    ).first
  end




  private
  def deny_destroy_if_last
    is_last = User.count == 1
    if is_last
      errors.add(:base, 'Cannot destroy last user')
    end
    !is_last
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_current_user, :only => [:edit, :update, :destroy]
  before_action :set_user, :only => [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end


  def show
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user), :flash => { :success => 'User created' }
    else
      flash.now[:error] = 'User not created'
      render :new
    end
  end


  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), :flash => { :success => 'User updated' }
    else
      flash.now[:error] = 'User not updated'
      render :edit
    end
  end


  def destroy
    # TODO a user should not be signed out if it is the last user and destroy is attempted
    sign_out_if_current_user
    if @user.destroy
      flash[:success] = 'User destroyed'
    else
      flash[:error] = 'User not destroyed: ' +
        @user.errors.full_messages.join(', ')
    end
    redirect_to root_path
  end




  private
  def set_user
    if action_name == 'show'
      @user = User.find_by_id(params[:id])
    else
      @user = current_user
    end
    redirect_to root_path, :flash => { :error => 'Unable to find user' } unless @user
  end


  def user_params
    params.require(:user).permit(
      :email,
      :username,
      :password,
      :password_confirmation
    )
  end


  def sign_out_if_current_user
    if is_current_user?(@user)
      unless sign_out
        flash[:error] = 'Unable to sign out user'
        redirect_to admin_users_path
      end
    end
  end


  def require_current_user
    unless params[:id].to_i == current_user.id.to_i
      flash[:error] = 'You are unauthorized to perform that action'
      redirect_to root_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= render :partial => 'admin/shared/errors', :locals => { :object => user } %>

<%= form_for([:admin, user]) do |f| %>

  <% if user.persisted? %>
    <div class="form-group">
      <h2 class="form-control-static"><em>ID:</em> <%= user.id %></h2>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label(:username) %>
    <%= f.text_field(:username, :class => 'form-control') %>
  </div>

  <div class="form-group">
    <%= f.label(:email) %>
    <%= f.text_field(:email, :class => 'form-control') %>
  </div>

  <div class="form-group">
    <%= f.label(:password) %>
    <%= f.password_field(:password, :class => 'form-control') %>
  </div>

  <div class="form-group">
    <%= f.label(:password_confirmation) %>
    <%= f.password_field(:password_confirmation, :class => 'form-control') %>
  </div>

  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

app/views/admin/users/edit.html.erb
<header class="page-header">
  <h1>
    <%= fa('user') %> Edit User
  </h1>
</header>

<%= render :partial => 'form', :locals => { :user => @user } %>

app/views/admin/users/index.html.erb
<header class="page-header">
  <h1>
    <%= fa('user') %> Users
    <small>
      <%= link_to(fa('plus') + ' New User', new_admin_user_path) %>
    </small>
  </h1>
</header>


<% if @users.present? %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th><th>Username</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to(user.username, admin_user_path(user)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p class="text-danger">Why for are there no more users no more?</p>

<% end %>

app/views/admin/users/new.html.erb
<header class="page-header">
  <h1>
    <%= fa('user') %> New User
  </h1>
</header>

<%= render :partial => 'form', :locals => { :user => @user } %>

app/views/admin/users/show.html.erb
<header class="page-header">
  <h1>
    <%= fa('user') %> User
    <small>
      <%= link_to(@user.username, admin_user_path(@user)) %>
    </small>
  </h1>
</header>

<div class="actions">
  <%= link_to(fa('pencil-square-o') + ' Edit', edit_admin_user_path(@user), :class => 'btn btn-default') %>
  <%= link_to(fa('close') + ' Delete', admin_user_path(@user), :method => :delete, :class => 'btn btn-danger') %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Key</th><th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>ID</td><td><%= @user.id %></td>
    </tr>
    <tr>
      <td>Username</td><td><%= @user.username %></td>
    </tr>
    <tr>
      <td>Email</td><td><%= @user.email %></td>
    </tr>
  </tbody>
</table>